package com.proint1.udea.produccion.entidades;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbPrdTipoproduccionesxcampo generated by hbm2java
 */
public class TbPrdTipoproduccionesxcampo implements java.io.Serializable {

	private long nbIdn;
	private TbPrdCampos tbPrdCampos;
	private TbPrdTipoproduccion tbPrdTipoproduccion;
	private char blEstado;
	private String vrAdtusuario;
	private Date dtAdtfecha;
	private Character blCampoobligatorio;
	private Set tbPrdDetalleproduccioneses = new HashSet(0);

	public TbPrdTipoproduccionesxcampo() {
	}

	public TbPrdTipoproduccionesxcampo(long nbIdn, TbPrdCampos tbPrdCampos,
			TbPrdTipoproduccion tbPrdTipoproduccion, char blEstado,
			String vrAdtusuario, Date dtAdtfecha) {
		this.nbIdn = nbIdn;
		this.tbPrdCampos = tbPrdCampos;
		this.tbPrdTipoproduccion = tbPrdTipoproduccion;
		this.blEstado = blEstado;
		this.vrAdtusuario = vrAdtusuario;
		this.dtAdtfecha = dtAdtfecha;
	}

	public TbPrdTipoproduccionesxcampo(long nbIdn, TbPrdCampos tbPrdCampos,
			TbPrdTipoproduccion tbPrdTipoproduccion, char blEstado,
			String vrAdtusuario, Date dtAdtfecha, Character blCampoobligatorio,
			Set tbPrdDetalleproduccioneses) {
		this.nbIdn = nbIdn;
		this.tbPrdCampos = tbPrdCampos;
		this.tbPrdTipoproduccion = tbPrdTipoproduccion;
		this.blEstado = blEstado;
		this.vrAdtusuario = vrAdtusuario;
		this.dtAdtfecha = dtAdtfecha;
		this.blCampoobligatorio = blCampoobligatorio;
		this.tbPrdDetalleproduccioneses = tbPrdDetalleproduccioneses;
	}

	public long getNbIdn() {
		return this.nbIdn;
	}

	public void setNbIdn(long nbIdn) {
		this.nbIdn = nbIdn;
	}

	public TbPrdCampos getTbPrdCampos() {
		return this.tbPrdCampos;
	}

	public void setTbPrdCampos(TbPrdCampos tbPrdCampos) {
		this.tbPrdCampos = tbPrdCampos;
	}

	public TbPrdTipoproduccion getTbPrdTipoproduccion() {
		return this.tbPrdTipoproduccion;
	}

	public void setTbPrdTipoproduccion(TbPrdTipoproduccion tbPrdTipoproduccion) {
		this.tbPrdTipoproduccion = tbPrdTipoproduccion;
	}

	public char getBlEstado() {
		return this.blEstado;
	}

	public void setBlEstado(char blEstado) {
		this.blEstado = blEstado;
	}

	public String getVrAdtusuario() {
		return this.vrAdtusuario;
	}

	public void setVrAdtusuario(String vrAdtusuario) {
		this.vrAdtusuario = vrAdtusuario;
	}

	public Date getDtAdtfecha() {
		return this.dtAdtfecha;
	}

	public void setDtAdtfecha(Date dtAdtfecha) {
		this.dtAdtfecha = dtAdtfecha;
	}

	public Character getBlCampoobligatorio() {
		return this.blCampoobligatorio;
	}

	public void setBlCampoobligatorio(Character blCampoobligatorio) {
		this.blCampoobligatorio = blCampoobligatorio;
	}

	public Set getTbPrdDetalleproduccioneses() {
		return this.tbPrdDetalleproduccioneses;
	}

	public void setTbPrdDetalleproduccioneses(Set tbPrdDetalleproduccioneses) {
		this.tbPrdDetalleproduccioneses = tbPrdDetalleproduccioneses;
	}

}
