package com.proint1.udea.produccion.entidades;


// default package
// Generated 8/11/2014 11:56:05 AM by Hibernate Tools 4.0.0

/**
 * TbPrdMiembrosxgrupo generated by hbm2java
 */
public class TbPrdMiembrosxgrupo implements java.io.Serializable {

	private TbPrdMiembrosxgrupoId id;
	private TbPrdGrupoinvestigacion tbPrdGrupoinvestigacion;
	private TbPrdAutor tbPrdAutor;

	public TbPrdMiembrosxgrupo() {
	}

	public TbPrdMiembrosxgrupo(TbPrdMiembrosxgrupoId id,
			TbPrdGrupoinvestigacion tbPrdGrupoinvestigacion,
			TbPrdAutor tbPrdAutor) {
		this.id = id;
		this.tbPrdGrupoinvestigacion = tbPrdGrupoinvestigacion;
		this.tbPrdAutor = tbPrdAutor;
	}

	public TbPrdMiembrosxgrupoId getId() {
		return this.id;
	}

	public void setId(TbPrdMiembrosxgrupoId id) {
		this.id = id;
	}

	public TbPrdGrupoinvestigacion getTbPrdGrupoinvestigacion() {
		return this.tbPrdGrupoinvestigacion;
	}

	public void setTbPrdGrupoinvestigacion(
			TbPrdGrupoinvestigacion tbPrdGrupoinvestigacion) {
		this.tbPrdGrupoinvestigacion = tbPrdGrupoinvestigacion;
	}

	public TbPrdAutor getTbPrdAutor() {
		return this.tbPrdAutor;
	}

	public void setTbPrdAutor(TbPrdAutor tbPrdAutor) {
		this.tbPrdAutor = tbPrdAutor;
	}

}