package com.proint1.udea.produccion.entidades;

/**
 * TbPrdAutoresxproduccion generated by hbm2java
 */
public class TbPrdAutoresxproduccion implements java.io.Serializable {

	private long nbAppIdn;
	private TbPrdProduccion tbPrdProduccion;
	private TbPrdAutor tbPrdAutor;

	public TbPrdAutoresxproduccion() {
	}

	public TbPrdAutoresxproduccion(long nbAppIdn,
			TbPrdProduccion tbPrdProduccion, TbPrdAutor tbPrdAutor) {
		this.nbAppIdn = nbAppIdn;
		this.tbPrdProduccion = tbPrdProduccion;
		this.tbPrdAutor = tbPrdAutor;
	}

	public long getNbAppIdn() {
		return this.nbAppIdn;
	}

	public void setNbAppIdn(long nbAppIdn) {
		this.nbAppIdn = nbAppIdn;
	}

	public TbPrdProduccion getTbPrdProduccion() {
		return this.tbPrdProduccion;
	}

	public void setTbPrdProduccion(TbPrdProduccion tbPrdProduccion) {
		this.tbPrdProduccion = tbPrdProduccion;
	}

	public TbPrdAutor getTbPrdAutor() {
		return this.tbPrdAutor;
	}

	public void setTbPrdAutor(TbPrdAutor tbPrdAutor) {
		this.tbPrdAutor = tbPrdAutor;
	}

}
