package com.proint1.udea.produccion.entidades;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbPrdProduccion generated by hbm2java
 */
public class TbPrdProduccion implements java.io.Serializable {

	private long nbIdn;
	private TbPrdTipoproduccion tbPrdTipoproduccion;
	private String vrNombreproduccion;
	private Date dtFechapublicacion;
	private String vrUrl;
	private String vrDoi;
	private char blEstado;
	private String vrAdtusuario;
	private Date dtAdtfecha;
	private Set tbPrdDetalleproduccioneses = new HashSet(0);
	private Set tbPrdAutoresxproduccions = new HashSet(0);

	public TbPrdProduccion() {
	}

	public TbPrdProduccion(long nbIdn, TbPrdTipoproduccion tbPrdTipoproduccion,
			String vrNombreproduccion, Date dtFechapublicacion, char blEstado,
			String vrAdtusuario, Date dtAdtfecha) {
		this.nbIdn = nbIdn;
		this.tbPrdTipoproduccion = tbPrdTipoproduccion;
		this.vrNombreproduccion = vrNombreproduccion;
		this.dtFechapublicacion = dtFechapublicacion;
		this.blEstado = blEstado;
		this.vrAdtusuario = vrAdtusuario;
		this.dtAdtfecha = dtAdtfecha;
	}

	public TbPrdProduccion(long nbIdn, TbPrdTipoproduccion tbPrdTipoproduccion,
			String vrNombreproduccion, Date dtFechapublicacion, String vrUrl,
			String vrDoi, char blEstado, String vrAdtusuario, Date dtAdtfecha,
			Set tbPrdDetalleproduccioneses, Set tbPrdAutoresxproduccions) {
		this.nbIdn = nbIdn;
		this.tbPrdTipoproduccion = tbPrdTipoproduccion;
		this.vrNombreproduccion = vrNombreproduccion;
		this.dtFechapublicacion = dtFechapublicacion;
		this.vrUrl = vrUrl;
		this.vrDoi = vrDoi;
		this.blEstado = blEstado;
		this.vrAdtusuario = vrAdtusuario;
		this.dtAdtfecha = dtAdtfecha;
		this.tbPrdDetalleproduccioneses = tbPrdDetalleproduccioneses;
		this.tbPrdAutoresxproduccions = tbPrdAutoresxproduccions;
	}

	public long getNbIdn() {
		return this.nbIdn;
	}

	public void setNbIdn(long nbIdn) {
		this.nbIdn = nbIdn;
	}

	public TbPrdTipoproduccion getTbPrdTipoproduccion() {
		return this.tbPrdTipoproduccion;
	}

	public void setTbPrdTipoproduccion(TbPrdTipoproduccion tbPrdTipoproduccion) {
		this.tbPrdTipoproduccion = tbPrdTipoproduccion;
	}

	public String getVrNombreproduccion() {
		return this.vrNombreproduccion;
	}

	public void setVrNombreproduccion(String vrNombreproduccion) {
		this.vrNombreproduccion = vrNombreproduccion;
	}

	public Date getDtFechapublicacion() {
		return this.dtFechapublicacion;
	}

	public void setDtFechapublicacion(Date dtFechapublicacion) {
		this.dtFechapublicacion = dtFechapublicacion;
	}

	public String getVrUrl() {
		return this.vrUrl;
	}

	public void setVrUrl(String vrUrl) {
		this.vrUrl = vrUrl;
	}

	public String getVrDoi() {
		return this.vrDoi;
	}

	public void setVrDoi(String vrDoi) {
		this.vrDoi = vrDoi;
	}

	public char getBlEstado() {
		return this.blEstado;
	}

	public void setBlEstado(char blEstado) {
		this.blEstado = blEstado;
	}

	public String getVrAdtusuario() {
		return this.vrAdtusuario;
	}

	public void setVrAdtusuario(String vrAdtusuario) {
		this.vrAdtusuario = vrAdtusuario;
	}

	public Date getDtAdtfecha() {
		return this.dtAdtfecha;
	}

	public void setDtAdtfecha(Date dtAdtfecha) {
		this.dtAdtfecha = dtAdtfecha;
	}

	public Set getTbPrdDetalleproduccioneses() {
		return this.tbPrdDetalleproduccioneses;
	}

	public void setTbPrdDetalleproduccioneses(Set tbPrdDetalleproduccioneses) {
		this.tbPrdDetalleproduccioneses = tbPrdDetalleproduccioneses;
	}

	public Set getTbPrdAutoresxproduccions() {
		return this.tbPrdAutoresxproduccions;
	}

	public void setTbPrdAutoresxproduccions(Set tbPrdAutoresxproduccions) {
		this.tbPrdAutoresxproduccions = tbPrdAutoresxproduccions;
	}

}
