package com.proint1.udea.produccion.entidades;

/**
 * TbPrdAutoresxproduccionId generated by hbm2java
 */
public class TbPrdAutoresxproduccionId implements java.io.Serializable {

	private static final long serialVersionUID = 8228473124434693122L;
	
	private long nbProIdn;
	private long nbAutIdn;

	public TbPrdAutoresxproduccionId() {
	}

	public TbPrdAutoresxproduccionId(long nbProIdn, long nbAutIdn) {
		this.nbProIdn = nbProIdn;
		this.nbAutIdn = nbAutIdn;
	}

	public long getNbProIdn() {
		return this.nbProIdn;
	}

	public void setNbProIdn(long nbProIdn) {
		this.nbProIdn = nbProIdn;
	}

	public long getNbAutIdn() {
		return this.nbAutIdn;
	}

	public void setNbAutIdn(long nbAutIdn) {
		this.nbAutIdn = nbAutIdn;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbPrdAutoresxproduccionId))
			return false;
		TbPrdAutoresxproduccionId castOther = (TbPrdAutoresxproduccionId) other;

		return (this.getNbProIdn() == castOther.getNbProIdn())
				&& (this.getNbAutIdn() == castOther.getNbAutIdn());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getNbProIdn();
		result = 37 * result + (int) this.getNbAutIdn();
		return result;
	}

}
