package com.proint1.udea.produccion.entidades;

import com.proint1.udea.administracion.entidades.terceros.Pais;
import com.proint1.udea.administracion.entidades.terceros.Persona;

/**
 * Autor generated by hbm2java
 */
public class TbPrdAutor implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private long id;
	private Pais pais;
	private Persona persona;

	public TbPrdAutor() {
	}

	public TbPrdAutor(Pais pais, Persona persona) {
		this.pais = pais;
		this.persona = persona;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Pais getPais() {
		return this.pais;
	}

	public void setPais(Pais pais) {
		this.pais = pais;
	}

	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}
}
