package com.proint1.udea.produccion.entidades;

import java.util.Date;

/**
 * TbPrdTipoproducionesxcampo generated by hbm2java
 */
public class TbPrdTipoproducionesxcampo implements java.io.Serializable {

	private long nbIdn;
	private TbPrdCampo tbPrdCampo;
	private TbPrdTipoproduccion nbTipoproduccion;
	private String vrAdtusuario;
	private Date dtAdtfecha;

	public TbPrdTipoproducionesxcampo() {
	}

	public TbPrdTipoproducionesxcampo(long nbIdn, TbPrdCampo tbPrdCampo,
			TbPrdTipoproduccion tbPrdTipoproduccion, String vrAdtusuario,
			Date dtAdtfecha) {
		this.nbIdn = nbIdn;
		this.tbPrdCampo = tbPrdCampo;
		this.nbTipoproduccion = tbPrdTipoproduccion;
		this.vrAdtusuario = vrAdtusuario;
		this.dtAdtfecha = dtAdtfecha;
	}

	public long getNbIdn() {
		return this.nbIdn;
	}

	public void setNbIdn(long nbIdn) {
		this.nbIdn = nbIdn;
	}

	public TbPrdCampo getTbPrdCampo() {
		return this.tbPrdCampo;
	}

	public void setTbPrdCampo(TbPrdCampo tbPrdCampos) {
		this.tbPrdCampo = tbPrdCampos;
	}
	
	

	public TbPrdTipoproduccion getNbTipoproduccion() {
		return nbTipoproduccion;
	}

	public void setNbTipoproduccion(TbPrdTipoproduccion nbTipoproduccion) {
		this.nbTipoproduccion = nbTipoproduccion;
	}

	public String getVrAdtusuario() {
		return this.vrAdtusuario;
	}

	public void setVrAdtusuario(String vrAdtusuario) {
		this.vrAdtusuario = vrAdtusuario;
	}

	public Date getDtAdtfecha() {
		return this.dtAdtfecha;
	}

	public void setDtAdtfecha(Date dtAdtfecha) {
		this.dtAdtfecha = dtAdtfecha;
	}


}
