package com.proint1.udea.produccion.entidades;

/**
 * TbPrdMiembrosxgrupoId generated by hbm2java
 */
public class TbPrdMiembrosxgrupoId implements java.io.Serializable {

	private long nbGpiIdn;
	private long nbPerIdn;
	private long nbConsecutivo;

	public TbPrdMiembrosxgrupoId() {
	}

	public TbPrdMiembrosxgrupoId(long nbGpiIdn, long nbPerIdn,
			long nbConsecutivo) {
		this.nbGpiIdn = nbGpiIdn;
		this.nbPerIdn = nbPerIdn;
		this.nbConsecutivo = nbConsecutivo;
	}

	public long getNbGpiIdn() {
		return this.nbGpiIdn;
	}

	public void setNbGpiIdn(long nbGpiIdn) {
		this.nbGpiIdn = nbGpiIdn;
	}

	public long getNbPerIdn() {
		return this.nbPerIdn;
	}

	public void setNbPerIdn(long nbPerIdn) {
		this.nbPerIdn = nbPerIdn;
	}

	public long getNbConsecutivo() {
		return this.nbConsecutivo;
	}

	public void setNbConsecutivo(long nbConsecutivo) {
		this.nbConsecutivo = nbConsecutivo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbPrdMiembrosxgrupoId))
			return false;
		TbPrdMiembrosxgrupoId castOther = (TbPrdMiembrosxgrupoId) other;

		return (this.getNbGpiIdn() == castOther.getNbGpiIdn())
				&& (this.getNbPerIdn() == castOther.getNbPerIdn())
				&& (this.getNbConsecutivo() == castOther.getNbConsecutivo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getNbGpiIdn();
		result = 37 * result + (int) this.getNbPerIdn();
		result = 37 * result + (int) this.getNbConsecutivo();
		return result;
	}

}
