package com.proint1.udea.produccion.entidades;

import java.util.Date;

import com.proint1.udea.administracion.entidades.terceros.TbAdmPersona;

/**
 * TbPrdMiembrosxgrupo generated by hbm2java
 */
public class TbPrdMiembrosxgrupo implements java.io.Serializable {

	private TbPrdMiembrosxgrupoId id;
	private TbPrdGrupoinvestigacion tbPrdGrupoinvestigacion;
	private TbAdmPersona tbAdmPersona;
	private Date dtFechacreacion;
	private String blEstado;
	private Date dtFecharetiro;
	private String vrAdtusuario;
	private Date dtAdtfecha;

	public TbPrdMiembrosxgrupo() {
	}

	public TbPrdMiembrosxgrupo(TbPrdMiembrosxgrupoId id,
			TbPrdGrupoinvestigacion tbPrdGrupoinvestigacion,
			TbAdmPersona tbAdmPersona, Date dtFechacreacion, String blEstado,
			String vrAdtusuario, Date dtAdtfecha) {
		this.id = id;
		this.tbPrdGrupoinvestigacion = tbPrdGrupoinvestigacion;
		this.tbAdmPersona = tbAdmPersona;
		this.dtFechacreacion = dtFechacreacion;
		this.blEstado = blEstado;
		this.vrAdtusuario = vrAdtusuario;
		this.dtAdtfecha = dtAdtfecha;
	}

	public TbPrdMiembrosxgrupo(TbPrdMiembrosxgrupoId id,
			TbPrdGrupoinvestigacion tbPrdGrupoinvestigacion,
			TbAdmPersona tbAdmPersona, Date dtFechacreacion, String blEstado,
			Date dtFecharetiro, String vrAdtusuario, Date dtAdtfecha) {
		this.id = id;
		this.tbPrdGrupoinvestigacion = tbPrdGrupoinvestigacion;
		this.tbAdmPersona = tbAdmPersona;
		this.dtFechacreacion = dtFechacreacion;
		this.blEstado = blEstado;
		this.dtFecharetiro = dtFecharetiro;
		this.vrAdtusuario = vrAdtusuario;
		this.dtAdtfecha = dtAdtfecha;
	}

	public TbPrdMiembrosxgrupoId getId() {
		return this.id;
	}

	public void setId(TbPrdMiembrosxgrupoId id) {
		this.id = id;
	}

	public TbPrdGrupoinvestigacion getTbPrdGrupoinvestigacion() {
		return this.tbPrdGrupoinvestigacion;
	}

	public void setTbPrdGrupoinvestigacion(
			TbPrdGrupoinvestigacion tbPrdGrupoinvestigacion) {
		this.tbPrdGrupoinvestigacion = tbPrdGrupoinvestigacion;
	}

	public TbAdmPersona getTbAdmPersona() {
		return this.tbAdmPersona;
	}

	public void setTbAdmPersona(TbAdmPersona tbAdmPersona) {
		this.tbAdmPersona = tbAdmPersona;
	}

	public Date getDtFechacreacion() {
		return this.dtFechacreacion;
	}

	public void setDtFechacreacion(Date dtFechacreacion) {
		this.dtFechacreacion = dtFechacreacion;
	}

	public String getBlEstado() {
		return this.blEstado;
	}

	public void setBlEstado(String blEstado) {
		this.blEstado = blEstado;
	}

	public Date getDtFecharetiro() {
		return this.dtFecharetiro;
	}

	public void setDtFecharetiro(Date dtFecharetiro) {
		this.dtFecharetiro = dtFecharetiro;
	}

	public String getVrAdtusuario() {
		return this.vrAdtusuario;
	}

	public void setVrAdtusuario(String vrAdtusuario) {
		this.vrAdtusuario = vrAdtusuario;
	}

	public Date getDtAdtfecha() {
		return this.dtAdtfecha;
	}

	public void setDtAdtfecha(Date dtAdtfecha) {
		this.dtAdtfecha = dtAdtfecha;
	}

}
