package com.proint1.udea.produccion.entidades;

// default package
// Generated 8/11/2014 11:56:05 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * TbPrdHistoriamiembros generated by hbm2java
 */
public class TbPrdHistoriamiembros implements java.io.Serializable {

	private TbPrdHistoriamiembrosId id;
	private TbPrdGrupoinvestigacion tbPrdGrupoinvestigacion;
	private TbPrdAutor tbPrdAutor;
	private String vrAccion;
	private String vrDetalles;
	private String vrAdtusuario;
	private Date dtAdtfecha;

	public TbPrdHistoriamiembros() {
	}

	public TbPrdHistoriamiembros(TbPrdHistoriamiembrosId id,
			TbPrdGrupoinvestigacion tbPrdGrupoinvestigacion,
			TbPrdAutor tbPrdAutor, String vrAccion, String vrAdtusuario,
			Date dtAdtfecha) {
		this.id = id;
		this.tbPrdGrupoinvestigacion = tbPrdGrupoinvestigacion;
		this.tbPrdAutor = tbPrdAutor;
		this.vrAccion = vrAccion;
		this.vrAdtusuario = vrAdtusuario;
		this.dtAdtfecha = dtAdtfecha;
	}

	public TbPrdHistoriamiembros(TbPrdHistoriamiembrosId id,
			TbPrdGrupoinvestigacion tbPrdGrupoinvestigacion,
			TbPrdAutor tbPrdAutor, String vrAccion, String vrDetalles,
			String vrAdtusuario, Date dtAdtfecha) {
		this.id = id;
		this.tbPrdGrupoinvestigacion = tbPrdGrupoinvestigacion;
		this.tbPrdAutor = tbPrdAutor;
		this.vrAccion = vrAccion;
		this.vrDetalles = vrDetalles;
		this.vrAdtusuario = vrAdtusuario;
		this.dtAdtfecha = dtAdtfecha;
	}

	public TbPrdHistoriamiembrosId getId() {
		return this.id;
	}

	public void setId(TbPrdHistoriamiembrosId id) {
		this.id = id;
	}

	public TbPrdGrupoinvestigacion getTbPrdGrupoinvestigacion() {
		return this.tbPrdGrupoinvestigacion;
	}

	public void setTbPrdGrupoinvestigacion(
			TbPrdGrupoinvestigacion tbPrdGrupoinvestigacion) {
		this.tbPrdGrupoinvestigacion = tbPrdGrupoinvestigacion;
	}

	public TbPrdAutor getTbPrdAutor() {
		return this.tbPrdAutor;
	}

	public void setTbPrdAutor(TbPrdAutor tbPrdAutor) {
		this.tbPrdAutor = tbPrdAutor;
	}

	public String getVrAccion() {
		return this.vrAccion;
	}

	public void setVrAccion(String vrAccion) {
		this.vrAccion = vrAccion;
	}

	public String getVrDetalles() {
		return this.vrDetalles;
	}

	public void setVrDetalles(String vrDetalles) {
		this.vrDetalles = vrDetalles;
	}

	public String getVrAdtusuario() {
		return this.vrAdtusuario;
	}

	public void setVrAdtusuario(String vrAdtusuario) {
		this.vrAdtusuario = vrAdtusuario;
	}

	public Date getDtAdtfecha() {
		return this.dtAdtfecha;
	}

	public void setDtAdtfecha(Date dtAdtfecha) {
		this.dtAdtfecha = dtAdtfecha;
	}

}
