// default package
// Generated 17/10/2014 09:41:12 AM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbPrdTipoproduccion generated by hbm2java
 */
public class TbPrdTipoproduccion implements java.io.Serializable {

	private long nbIdn;
	private String vrDescripcion;
	private char blEstado;
	private String vrAdtusuario;
	private Date dtAdtfecha;
	private Set tbPrdProduccions = new HashSet(0);
	private Set tbPrdTipoproduccionesxcampos = new HashSet(0);

	public TbPrdTipoproduccion() {
	}

	public TbPrdTipoproduccion(long nbIdn, String vrDescripcion, char blEstado,
			String vrAdtusuario, Date dtAdtfecha) {
		this.nbIdn = nbIdn;
		this.vrDescripcion = vrDescripcion;
		this.blEstado = blEstado;
		this.vrAdtusuario = vrAdtusuario;
		this.dtAdtfecha = dtAdtfecha;
	}

	public TbPrdTipoproduccion(long nbIdn, String vrDescripcion, char blEstado,
			String vrAdtusuario, Date dtAdtfecha, Set tbPrdProduccions,
			Set tbPrdTipoproduccionesxcampos) {
		this.nbIdn = nbIdn;
		this.vrDescripcion = vrDescripcion;
		this.blEstado = blEstado;
		this.vrAdtusuario = vrAdtusuario;
		this.dtAdtfecha = dtAdtfecha;
		this.tbPrdProduccions = tbPrdProduccions;
		this.tbPrdTipoproduccionesxcampos = tbPrdTipoproduccionesxcampos;
	}

	public long getNbIdn() {
		return this.nbIdn;
	}

	public void setNbIdn(long nbIdn) {
		this.nbIdn = nbIdn;
	}

	public String getVrDescripcion() {
		return this.vrDescripcion;
	}

	public void setVrDescripcion(String vrDescripcion) {
		this.vrDescripcion = vrDescripcion;
	}

	public char getBlEstado() {
		return this.blEstado;
	}

	public void setBlEstado(char blEstado) {
		this.blEstado = blEstado;
	}

	public String getVrAdtusuario() {
		return this.vrAdtusuario;
	}

	public void setVrAdtusuario(String vrAdtusuario) {
		this.vrAdtusuario = vrAdtusuario;
	}

	public Date getDtAdtfecha() {
		return this.dtAdtfecha;
	}

	public void setDtAdtfecha(Date dtAdtfecha) {
		this.dtAdtfecha = dtAdtfecha;
	}

	public Set getTbPrdProduccions() {
		return this.tbPrdProduccions;
	}

	public void setTbPrdProduccions(Set tbPrdProduccions) {
		this.tbPrdProduccions = tbPrdProduccions;
	}

	public Set getTbPrdTipoproduccionesxcampos() {
		return this.tbPrdTipoproduccionesxcampos;
	}

	public void setTbPrdTipoproduccionesxcampos(Set tbPrdTipoproduccionesxcampos) {
		this.tbPrdTipoproduccionesxcampos = tbPrdTipoproduccionesxcampos;
	}

}
