package com.proint1.udea.administracion.entidades.seguridad;
// default package
// Generated 10-may-2014 11:58:30 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import com.proint1.udea.administracion.entidades.terceros.Persona;

/**
 * TbAdmUsuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

	private long nbUsuIdn;
	private Persona tbAdmPersona;
	private String vrUsuLogin;
	private long nbUsuActivo;
	private Set tbAdmUsuarioxrols = new HashSet(0);

	public Usuario() {
	}

	public Usuario(long nbUsuIdn, Persona tbAdmPersona,
			String vrUsuLogin, long nbUsuActivo) {
		this.nbUsuIdn = nbUsuIdn;
		this.tbAdmPersona = tbAdmPersona;
		this.vrUsuLogin = vrUsuLogin;
		this.nbUsuActivo = nbUsuActivo;
	}

	public Usuario(long nbUsuIdn, Persona tbAdmPersona,
			String vrUsuLogin, long nbUsuActivo, Set tbAdmUsuarioxrols) {
		this.nbUsuIdn = nbUsuIdn;
		this.tbAdmPersona = tbAdmPersona;
		this.vrUsuLogin = vrUsuLogin;
		this.nbUsuActivo = nbUsuActivo;
		this.tbAdmUsuarioxrols = tbAdmUsuarioxrols;
	}

	public long getNbUsuIdn() {
		return this.nbUsuIdn;
	}

	public void setNbUsuIdn(long nbUsuIdn) {
		this.nbUsuIdn = nbUsuIdn;
	}

	public Persona getTbAdmPersona() {
		return this.tbAdmPersona;
	}

	public void setTbAdmPersona(Persona tbAdmPersona) {
		this.tbAdmPersona = tbAdmPersona;
	}

	public String getVrUsuLogin() {
		return this.vrUsuLogin;
	}

	public void setVrUsuLogin(String vrUsuLogin) {
		this.vrUsuLogin = vrUsuLogin;
	}

	public long getNbUsuActivo() {
		return this.nbUsuActivo;
	}

	public void setNbUsuActivo(long nbUsuActivo) {
		this.nbUsuActivo = nbUsuActivo;
	}

	public Set getTbAdmUsuarioxrols() {
		return this.tbAdmUsuarioxrols;
	}

	public void setTbAdmUsuarioxrols(Set tbAdmUsuarioxrols) {
		this.tbAdmUsuarioxrols = tbAdmUsuarioxrols;
	}

}
