package com.proint1.udea.administracion.entidades.terceros;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbAdmPaises generated by hbm2java
 */
public class TbAdmPaises implements java.io.Serializable {

	private long nbIdn;
	private String vrDescripcion;
	private String vrCodigo;
	private String vrAdtusuario;
	private Date dtAdtfecha;
	private Set tbPrdAutors = new HashSet(0);

	public TbAdmPaises() {
	}

	public TbAdmPaises(long nbIdn, String vrDescripcion, String vrCodigo,
			Date dtAdtfecha) {
		this.nbIdn = nbIdn;
		this.vrDescripcion = vrDescripcion;
		this.vrCodigo = vrCodigo;
		this.dtAdtfecha = dtAdtfecha;
	}

	public TbAdmPaises(long nbIdn, String vrDescripcion, String vrCodigo,
			String vrAdtusuario, Date dtAdtfecha, Set tbPrdAutors) {
		this.nbIdn = nbIdn;
		this.vrDescripcion = vrDescripcion;
		this.vrCodigo = vrCodigo;
		this.vrAdtusuario = vrAdtusuario;
		this.dtAdtfecha = dtAdtfecha;
		this.tbPrdAutors = tbPrdAutors;
	}

	public long getNbIdn() {
		return this.nbIdn;
	}

	public void setNbIdn(long nbIdn) {
		this.nbIdn = nbIdn;
	}

	public String getVrDescripcion() {
		return this.vrDescripcion;
	}

	public void setVrDescripcion(String vrDescripcion) {
		this.vrDescripcion = vrDescripcion;
	}

	public String getVrCodigo() {
		return this.vrCodigo;
	}

	public void setVrCodigo(String vrCodigo) {
		this.vrCodigo = vrCodigo;
	}

	public String getVrAdtusuario() {
		return this.vrAdtusuario;
	}

	public void setVrAdtusuario(String vrAdtusuario) {
		this.vrAdtusuario = vrAdtusuario;
	}

	public Date getDtAdtfecha() {
		return this.dtAdtfecha;
	}

	public void setDtAdtfecha(Date dtAdtfecha) {
		this.dtAdtfecha = dtAdtfecha;
	}

	public Set getTbPrdAutors() {
		return this.tbPrdAutors;
	}

	public void setTbPrdAutors(Set tbPrdAutors) {
		this.tbPrdAutors = tbPrdAutors;
	}

}
