package com.proint1.udea.administracion.entidades.terceros;

// default package
// Generated 17/10/2014 09:41:12 AM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbAdmTipoidentificacion generated by hbm2java
 */
public class TbAdmTipoIdentificacion implements java.io.Serializable {

	private long nbIdn;
	private Date dtAdtfecha;
	private String vrAdtusuario;
	private String vrDescripcion;
	private Set tbAdmPersonas = new HashSet(0);

	public TbAdmTipoIdentificacion() {
	}

	public TbAdmTipoIdentificacion(long nbIdn, Date dtAdtfecha,
			String vrAdtusuario, String vrDescripcion) {
		this.nbIdn = nbIdn;
		this.dtAdtfecha = dtAdtfecha;
		this.vrAdtusuario = vrAdtusuario;
		this.vrDescripcion = vrDescripcion;
	}

	public TbAdmTipoIdentificacion(long nbIdn, Date dtAdtfecha,
			String vrAdtusuario, String vrDescripcion, Set tbAdmPersonas) {
		this.nbIdn = nbIdn;
		this.dtAdtfecha = dtAdtfecha;
		this.vrAdtusuario = vrAdtusuario;
		this.vrDescripcion = vrDescripcion;
		this.tbAdmPersonas = tbAdmPersonas;
	}

	public long getNbIdn() {
		return this.nbIdn;
	}

	public void setNbIdn(long nbIdn) {
		this.nbIdn = nbIdn;
	}

	public Date getDtAdtfecha() {
		return this.dtAdtfecha;
	}

	public void setDtAdtfecha(Date dtAdtfecha) {
		this.dtAdtfecha = dtAdtfecha;
	}

	public String getVrAdtusuario() {
		return this.vrAdtusuario;
	}

	public void setVrAdtusuario(String vrAdtusuario) {
		this.vrAdtusuario = vrAdtusuario;
	}

	public String getVrDescripcion() {
		return this.vrDescripcion;
	}

	public void setVrDescripcion(String vrDescripcion) {
		this.vrDescripcion = vrDescripcion;
	}

	public Set getTbAdmPersonas() {
		return this.tbAdmPersonas;
	}

	public void setTbAdmPersonas(Set tbAdmPersonas) {
		this.tbAdmPersonas = tbAdmPersonas;
	}

}
